AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 100
    MemorySize: 6000
    ReservedConcurrentExecutions: 50
  # Api:
  #   BinaryMediaTypes:
  #     - image/png
  #     - image/jpg
  #     - image/jpeg
Resources:
  GetClassifyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Classify:
          Type: Api 
          Properties:
            RestApiId: !Ref GatekeeperApi
            Path: /classify_digit
            Method: post
      Policies: 
        - S3CrudPolicy:
            BucketName: !Ref S3ModelBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBClassifiedData
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBClassifiedData
          S3_BUCKET_NAME: !Ref S3ModelBucket
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./post_classify_image
      DockerTag: python3.9-v1
  GetCheckDbFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: get_db_check/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref PythonLibLayer
      MemorySize: 128
      Timeout: 1
      Architectures:
          - x86_64
      Events:
        CheckDB:
          Type: Api 
          Properties:
            RestApiId: !Ref GatekeeperApi
            Path: /check_db/{hash}
            Method: get
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBClassifiedData
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBClassifiedData
          S3_BUCKET_NAME: !Ref S3ModelBucket
  GatekeeperApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  S3ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      Tags:
        - Key: project
          Value: ma
  DynamoDBClassifiedData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: project
          Value: ma
  PythonLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lib_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InferenceApi:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${GatekeeperApi}.execute-api.${AWS::Region}.amazonaws.com/v1/"
  GetClassifyFunction:
    Description: "GetClassifyFunction Lambda Function ARN"
    Value: !GetAtt GetClassifyFunction.Arn
  GetCheckDbFunction:
    Description: "GetCheckDbFunction Lambda Function ARN"
    Value: !GetAtt GetCheckDbFunction.Arn


